services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    env_file:
      - .env
    command: >-
      sh -c "pnpm exec drizzle-kit migrate && node dist/index.mjs"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.3
    container_name: database
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
